---
systemNamespace: football-clubs-ns

traefikImageName: traefik
traefikImageTag: v3.0
traefikReplicasCount: 1
traefikProxyPort: 9090
traefikConfigPath: /etc/traefik

traefikSidecarApiDashboardEnabled: true
traefikSidecarApiInsecureEnabled: true

traefikResources:
  requestsCpu: 200m
  requestsMemory: 256Mi
  limitsCpu: 400m
  limitsMemory: 512Mi

proxyAppSrvName: football-clubs-svc
proxyAppNs: football-clubs-ns
proxyAppSidecarEnable: false
proxyAppPort: 8090
proxyAppWithSidecarPort: 9090