version: "3"

services:
  football_clubs_app:
    build:
      context: .
      dockerfile: Dockerfile
    image: football_clubs
    environment:
      - UVICORN_PORT=8080
    networks:
      - football_clubs_network
    ports:
      - "8080:8080"

networks:
  football_clubs_network: