---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-cm
  namespace: {{ .Values.systemNamespace }}
  labels:
    {{- include "traefic-proxy.default-labels" . | indent 4 }}
data:
  routes.toml: |-
    [http]
      [http.middlewares]
        [http.middlewares.api-stripprefix.stripPrefix]
          prefixes = ["/docs", "/redoc"]
    [http.routers.app-router]
      entryPoints = ["http"]
      rule = "PathPrefix(`/`)"
      service = "service-app"
      middlewares = ["api-stripprefix"]
    [http.services]
      [http.services.service-app]
        [http.services.service-app.loadBalancer]
          [[http.services.service-app.loadBalancer.servers]]
            {{- include "traefic-proxy.proxy-application-service" . | indent 12 }}
  traefik.toml: |-
    [entryPoints]
      [entryPoints.http]
        address = ":{{ .Values.traefikProxyPort }}"

    [providers]
      [providers.file]
        filename = "{{ .Values.traefikConfigPath }}/routes.toml"

    [api]
      dashboard = {{ .Values.traefikSidecarApiDashboardEnabled }}
      insecure = {{ .Values.traefikSidecarApiInsecureEnabled }}