---
systemNamespace: football-clubs-ns
systemRegistry: skay1989
systemContainerName: football_clubs

appReplicasCount: 2
appHttpPort: 8090
appResources:
  requestsCpu: 200m
  requestsMemory: 256Mi
  limitsCpu: 400m
  limitsMemory: 512Mi

traefikSidecarEnabled: false
traefikSidecarAppHttpPort: 9090
traefikSidecarApiDashboardEnabled: true
traefikSidecarApiInsecureEnabled: true
traefikSidecarImageName: traefik
traefikSidecarImageTag: v3.0
traefikSidecarConfigsPath: /etc/traefik
traefikSidecatResources:
  requestsCpu: 200m
  requestsMemory: 256Mi
  limitsCpu: 400m
  limitsMemory: 512Mi