---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-env-cm
  namespace: {{ .Values.global.systemNamespace }}
  labels:
    app: {{ .Chart.Name }}
    {{- include "football-clubs-app.labels" . | indent 4 }}
data:
  {{- range $key, $val := .Values.appEnv }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}