---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-deploy
  namespace: {{ .Values.global.systemNamespace }}
  labels:
    app: {{ .Chart.Name }}
    {{- include "football-clubs-app.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicasCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      name: {{ .Chart.Name }}
      labels:
        app: {{ .Chart.Name }}
        {{- include "football-clubs-app.labels" . | indent 8 }}
    spec:
      {{- if .Values.traefikSidecarEnabled }}
      volumes:
        - name: {{ .Chart.Name }}-traefik-proxy-config-cm-volume
          configMap:
            name: {{ .Chart.Name }}-traefik-proxy-config-cm
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.appImageRegistry }}/{{ .Values.appImageName }}:{{ template "football-clubs-app.application-version" . }}"
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: {{ .Chart.Name }}-env-cm
          {{- if not .Values.traefikSidecarEnabled }}
          ports:
            - containerPort: {{ .Values.appPort }}
              protocol: TCP
          {{- end }}
          {{- with .Values.appResources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- if .Values.traefikSidecarEnabled }}
        - name: {{ .Chart.Name }}-traefik-proxy
          image: "{{ .Values.traefikSidecarImageName }}:{{ .Values.global.traefikProxyImageVersion }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.traefikSidecarPort }}
              protocol: TCP
            - containerPort: {{ .Values.traefikSidecarDashboardPort }}
              protocol: TCP
          {{- with .Values.traefikSidecarResources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - mountPath: {{ .Values.traefikSidecarConfigsPath }}
              name: {{ .Chart.Name }}-traefik-proxy-config-cm-volume
        {{- end }}
      restartPolicy: Always