---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-deploy
  namespace: {{ .Values.global.systemNamespace }}
  labels:
    app: {{ .Chart.Name }}
    {{- include "traefic-proxy.default-labels" . | indent 4 }}
spec:
  replicas: {{ .Values.traefikReplicasCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      name: {{ .Chart.Name }}
      labels:
        app: {{ .Chart.Name }}
        {{- include "traefic-proxy.default-labels" . | indent 8 }}
    spec:
      volumes:
        - name: {{ .Chart.Name }}-traefik-proxy-config-cm-volume
          configMap:
            name: {{ .Chart.Name }}-traefik-proxy-config-cm
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.traefikImageName }}:{{ .Values.global.traefikProxyImageVersion }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.traefikProxyPort }}
              protocol: TCP
            - containerPort: {{ .Values.traefikProxyDashboardPort }}
              protocol: TCP
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - mountPath: {{ .Values.traefikConfigPath }}
              name: {{ .Chart.Name }}-traefik-proxy-config-cm-volume
      restartPolicy: Always
