---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-svc
  namespace: {{ .Values.global.systemNamespace }}
  labels:
    {{- include "traefic-proxy.default-labels" . | indent 4 }}
spec:
  ports:
    - port: {{ .Values.traefikProxyPort }}
      targetPort: {{ .Values.traefikProxyPort }}
      name: http
      protocol: TCP
    - port: {{ .Values.traefikProxyDashboardPort }}
      targetPort: {{ .Values.traefikProxyDashboardPort }}
      name: traefik-dashboard
      protocol: TCP
  type: ClusterIP
  selector:
    app: {{ .Chart.Name }}