---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-traefik-cm
  namespace: {{ .Values.systemNamespace }}
  labels:
    {{- include "football_clubs.default_labels" . | indent 4 }}
data:
  routes.toml: |-
    [http]
      [http.middlewares]
        [http.middlewares.api-stripprefix.stripPrefix]
          prefixes = ["/docs", "/redoc"]
      [http.routers.app-router]
        entryPoints = ["http"]
        rule = "PathPrefix(`/`)"
        service = "service-app"
        middlewares = ["api-stripprefix"]
      [http.services]
        [http.services.service-app]
          [http.services.service-app.loadBalancer]
            [[http.services.service-app.loadBalancer.servers]]
              url = "http://127.0.0.1:{{ .Values.appHttpPort }}"
  traefik.toml: |-
    [entryPoints]
      [entryPoints.http]
        address = ":{{ .Values.traefikSidecarAppHttpPort }}"

    [providers]
      [providers.file]
        filename = "{{ .Values.traefikSidecarConfigsPath }}/routes.toml"

    [api]
      dashboard = {{ .Values.traefikSidecarApiDashboardEnabled }}
      insecure = {{ .Values.traefikSidecarApiInsecureEnabled }}