---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-deploy
  namespace: {{ .Values.systemNamespace }}
  labels:
    app: {{ .Chart.Name }}
    {{- include "football_clubs.default_labels" . | indent 4 }}
spec:
  replicas: {{ .Values.appReplicasCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      name: {{ .Chart.Name }}
      labels:
        app: {{ .Chart.Name }}
        {{- include "football_clubs.default_labels" . | indent 8 }}
    spec:
      {{- if .Values.traefikSidecarEnabled }}
      volumes:
        - name: {{ .Chart.Name }}-traefik-cm-volume
          configMap:
            name: {{ .Chart.Name }}-traefik-cm
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}-app
          image: "{{ .Values.systemRegistry }}/{{ .Values.systemContainerName }}:{{ .Chart.AppVersion}}"
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: {{ .Chart.Name }}-env-cm
          ports:
            {{- if eq .Values.traefikSidecarEnabled false }}
            - containerPort: {{ .Values.appHttpPort }}
              protocol: TCP
            {{- end }}
          resources:
            {{- include "football_clubs.application_resources" . | indent 12 }}
        {{- if .Values.traefikSidecarEnabled }}
        - name: {{ .Chart.Name }}-traefik-proxy
          image: "{{ .Values.traefikSidecarImageName }}:{{ .Values.traefikSidecarImageTag }}"
          ports:
            - containerPort: {{ .Values.traefikSidecarAppHttpPort }}
              protocol: TCP
          resources:
            {{- include "football_clubs.traefik_sidecar_resources" . | indent 12 }}
          volumeMounts:
            - mountPath: {{ .Values.traefikSidecarConfigsPath }}
              name: {{ .Chart.Name }}-traefik-cm-volume
        {{- end }}
      restartPolicy: Always