---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-svc
  namespace: {{ .Values.systemNamespace }}
  labels:
    {{- include "football_clubs.default_labels" . | indent 4 }}
spec:
  selector:
    app: {{ .Chart.Name }}
  ports:
    - protocol: TCP
      port: {{ .Values.appHttpPort }}
      targetPort: {{ .Values.appHttpPort }}
  type: ClusterIP
  